### ISSUE TITLE
FEATURE REQUEST: Add more Ansible groups

### ISSUE THREAD

**Issue by mattwilmott** [theforeman/foreman_ansible_inventory#5]
In addition to Hostgroup, Location and Organisation, it would be helpful if the following foreman derived facts were exposed as Ansible groups
- Domain
- Network and/or Subnet
- Environment
- OS Full Name
- OS Family

This would allow actions such as configuring sssd based on domain, configuring NFS shares per Network, patching an Environment, configuring a service based on RHEL version or Linux flavour.

**Comment by agx** [comment]
On Wed, Feb 24, 2016 at 03:58:00PM -0800, mattwilmott wrote:

> In addition to Hostgroup, Location and Organisation, it would be helpful if the following foreman derived facts were exposed as Ansible groups
> - Domain
> - Network and/or Subnet
> - Environment
> - OS Full Name
> - OS Family
> 
> This would allow actions such as configuring sssd based on domain, configuring NFS shares per Network, patching an Environment, configuring a service based on RHEL version or Linux flavour.

Sounds like a plan but instead of generating all of these I wonder if we
should not just expand these via our group_patterns. So far we only use
group params there but we could expand all hostvars there as well.

That would allow us to group by basially everything you have in
hostvars['foremen'] and one could e.g. build up things like

  {subnet_name}-{environment_name}-{image_name}

**Comment by mattwilmott** [comment]
That certainly sounds like a better idea

**Comment by agx** [comment]
https://github.com/theforeman/foreman_ansible_inventory/pull/7 should do the trick

**Comment by agx** [comment]
Sorry, ti's https://github.com/theforeman/foreman_ansible_inventory/pull/8
